// pub mod generate_gemma;
// pub mod create_account;
pub mod create_store;
pub mod update_store_sys_prompt;
pub mod get_stores;
pub mod delete_store;
pub mod login_account;
// pub mod update_products;
pub mod me;
pub mod logout_account;
pub mod get_store_products;
pub mod generation_demo;
pub mod add_products_to_store;
pub mod embed_table;
pub mod refresh_token;